version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ummah-auth-postgres
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ummah-auth-postgres
    ports:
      - "1000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
