version: "3.8"

services:
#  postgres:
#    image: postgres:14
#    container_name: ummah-postgres
#    restart: always
#    env_file:
#      - .env
#    environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "1000:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: ummah-backend
    ports:
      - "3035:3035"
#    depends_on:
#      - postgres
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require"
    restart: always

  user-panel:
    build:
      context: ./user-panel
    container_name: ummah-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./user-panel/.env
    restart: always

  admin-panel:
    build:
      context: ./admin-panel
    container_name: ummah-admin-panel
    ports:
      - "3001:3000"
    depends_on:
      - backend
    env_file:
      - ./admin-panel/.env
    restart: always

volumes:
  pgdata:
