server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:1000/users
    username: admin
    password: ummah-auth-postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: verySecretKey1234567890verySecretKey1234   # at least 32 chars
  refresh:
    secret: verySecretRefreshKey1234567890refreshKey
    expiration: 604800000                             # e.g., 7 days
  expiration: 86400000
